#version: '3.9'

services:
  mongoDB:
    image: mongo:latest
    container_name: diag-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    restart: always
    networks:
      - ms-network
  backend:
    image: dime/diag-terms-store:latest
    container_name: diag-terms-store
    ports:
      - "8081:8080"
    depends_on:
      - mongoDB
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - ms-network
networks:
  ms-network:
    external:
      name: diag-network
