#version: '3.9'

services:
  backend:
    image: dime/diag-terms-store:latest
    container_name: diag-terms-store
    ports:
      - "8083:8083"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PORT: 8083
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/api/health" ]
      interval: 300s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - postgres
    networks:
      - ms-network
    volumes:
      - backend-data:/var/lib/backend/data
  postgres:
    image: postgres:latest
    container_name: diag-terms-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: diag
      POSTGRES_USER: diag
      POSTGRES_PASSWORD: diag
    healthcheck:
      test: pg_isready -U diag
      interval: 300s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - ms-network
networks:
  ms-network:
    name: kafka-network
    external: true
volumes:
  backend-data:
  postgres-data: